python -m test.marl.test_centralv
python -m test.marl.test_coma
python -m test.marl.test_gru_centralv
python -m test.marl.test_gru_coma
python -m test.marl.test_gru_gru_centralv
python -m test.marl.test_gru_iac_simple
python -m test.marl.test_gru_iac
python -m test.marl.test_gru_ipg
python -m test.marl.test_gru_iql_se
python -m test.marl.test_gru_maddpg
python -m test.marl.test_gru_mixer
python -m test.marl.test_gru_seac
python -m test.marl.test_iac_seac
python -m test.marl.test_iac_full
python -m test.marl.test_ipg
python -m test.marl.test_iql_se
python -m test.marl.test_maddpg
python -m test.marl.test_mixer_multienv
python -m test.marl.test_mixer
